export const homeObjOne = {
    id: 'about',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: "About",
    headline: "",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis sed condimentum orci, in sagittis tortor. Maecenas aliquam nibh in odio aliquet, malesuada rutrum diam tempus. Nunc a neque id orci porttitor ornare ac vitae nibh. Nam sodales, risus at dictum feugiat, arcu diam congue libero, viverra porttitor enim lorem sit amet massa. Integer eget nulla quis eros iaculis consectetur tincidunt ut dolor. Fusce in mattis odio, ac commodo enim. Aliquam ornare quam nec velit dapibus ultricies.",
    buttonLabel: "Get Started",
    imgStart: true,
    img: require("../../images/about.svg").default,
    alt: "car",
    dark: true,
    primary: true,
    darkText: false,
}